import * as React from "react";
import { useState } from "react";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Link from "@mui/material/Link";
import CloseIcon from '@mui/icons-material/Close';
import { Box, Button, Dialog, DialogActions, DialogContent, DialogContentText } from "@mui/material";

export default function Footer() {
  const [openPolicyModal, setOpenPolicyModal] = useState(false);

	function TermsAndConditions(){
		return (
			<div>
				<p>
					<b>KnightAssist</b> is an <b>open-source</b> application available under Copyright (MIT License). The application in both its mobile and web versions uses data from both students and organizations at the <b>University of Central Florida (UCF)</b>. 
					The data collection starts from a voluntary registration on the platform by either student users or organization users considering that we <b>do not directly interact with the UCF databases</b> to obtain the information and data needed for the functioning of KnightAssist.
					The basic information we require upon sign up consists in the following:
				</p>
				<ul>
					<li>For users: first name, last name, username, email, password, alongside additional preference data.</li>
					<li>For organizations: organization name, username, email, password, alongside additional preference data.</li>
				</ul>
				<p>
					While most of the data we store and manipulate contains private information and IDs generated by us, we note that we <b>do
					not request data relevant to UCF including UCF ID, UCF NID, SSN, etc</b>. Regardless, the type of information we store still raises privacy concerns, which requires the encryption of
					this information to increase the security of the services our platform provides and insure the privacy of user and organization data. We implemented security measures 
					to have secure login, encrypted and safe data storage and account management. After conducting several tests, we can attest to the robustness of our approach to security 
					and privacy maintenance. Nevertheless, we are considering incorporating additional security measures including two-factor authentication, and even the usage of UCF’s SSO system if approval for that is granted.
				</p>
				<p>
					Considering the scope of our project, the intended goals from it, and the limitations that KnightAssist currently has, we are unable to allow users to fully customize 
					their accounts freely. We would have wanted to allow users from different backgrounds to use our application, however, we are <b>restricting access to UCF students, personnel, 
					and organizations</b>. Thus, by making this clear in our policies, licenses, and functionalities, we are ensuring that our data handling is efficient for UCF related entities. 
					Moreover, our development decisions were set to avoid any discrimination of any type, and our users can be of any gender and background. 
				</p>
				<p>
					We will explicitly include in our web and mobile apps privacy, ethics, and legal statements that the user will need to agree with. These will highlight the <b>data we collect, how it is used, what to expect from our application and services, 
					and we will prompt the user for their consent and retain it for our records</b>. Additionally, we will have routine evaluations to assess accounts using our app to control and survey any potential misuses of our app, and we <b>will ensure penalties for any 
					user or organization that will use KnightAssist for any unethical behaviors</b> that are essentially any behaviors that do not align with the purposes our app was built for initially. Moreover, we plan to provide admin accounts for any official UCF entity requesting to assess user and organization conduct through KnightAssist. 
				</p>
				<p>
					In summary, user and organization data will <b>not be used without permission</b>, and the data obtained will be stored and manipulated securely in our databases and processes. Information that we use for analysis, recommendation, and better user experiences will be <b>anonymized</b> to protect the 
					privacy of our users and retain their trust in us. Furthermore, as part of our mission and development we will allow users to <b>fully control the type and frequency of communications and notifications they receive</b>, and we will attempt to make our application as accessible as possible for the wider population of users.
				</p>
			</div>
		)
	}

  return (
    <Box sx={{display: 'flex', flexDirection: 'column', minWidth: '100%', bgcolor: '#5B526F', marginTop: 'auto'}}>
      <Container maxWidth="xl" sx={{p: 3}}>
        <Typography variant="body2" color="white" align="center">
          {"Copyright © "}
          <Link color="inherit" href="https://knightassist-43ab3aeaada9.herokuapp.com/">
            KnightAssist
          </Link>{" "}
          {new Date().getFullYear()}
          {"."}
          <a className="privatePolicy" onClick={() => setOpenPolicyModal(true)} style={{ color: 'white' }}>Terms & Conditions</a>
        </Typography>
      </Container>

      <Dialog open={openPolicyModal} onClose={() => setOpenPolicyModal(false)}>
        <DialogContent>
          <button className='closeAddEvent'>
                <CloseIcon onClick={() => setOpenPolicyModal(false)}/>
          </button>
          <DialogContentText className='contentWrap' style={{ color: 'black', fontSize: 25, marginBottom: 10, textAlign: 'center'}}>Terms & Conditions</DialogContentText>
          <DialogContentText className='contentWrap' style={{ color: 'black', marginTop: '10px', textAlign: 'justify' }}>
            <TermsAndConditions/>
          </DialogContentText>
        </DialogContent>
      </Dialog>
    </Box>
  );
}
